### ISSUE TITLE
[meta-warp7-distro] : New branch

### ISSUE THREAD

**Issue by texierp** [WaRP7/meta-warp7-distro#12]
Hi,

It's possible to create a new branch : pyro ?

Regards

Pierre-Jean

**Comment by WaRP7** [comment]
Hi,
Can you create it and make a "Pull requests"?

**Comment by WaRP7** [comment]
Hi texierp,
Done.

**Comment by texierp** [comment]
Hi,

Cool, thanks a lot :)

PJ

**Comment by texierp** [comment]
Hi,

It's possible to create a new branch : rocko ?

I've create it on my fork.

Regards

Pierre-Jean

**Comment by WaRP7** [comment]
Hi Pierre-Jean,
Done!
Branch "rocko" is from the current "master"

**Comment by texierp** [comment]
Thanks :)
