### ISSUE TITLE
fsl-community-bsp-platform: fork

### ISSUE THREAD

**Issue by texierp** [WaRP7/meta-warp7-distro#23]
Hi @WaRP7 ,

I would like know if we can fork the following repo : https://github.com/Freescale/fsl-community-bsp-platform into the WaRP7 repo ?

Allows to manage easily the following layers for developpers:
- meta-warp7-distro
- meta-qt5
- meta-swupdate

Thanks 

PJ

**Comment by zydz** [comment]
sorry to reply you so late. I have no permission of managing the repo of 
 _https://github.com/Freescale/fsl-community-bsp-platform_

**Comment by WaRP7** [comment]
Sorry to reply you so late. I have no permission of managing the repo of
 **https://github.com/Freescale/fsl-community-bsp-platform**

**Comment by texierp** [comment]
No problem :)

Yes, I imagine. I just want to know if it's possible to create a fork of this repo (https://github.com/Freescale/fsl-community-bsp-platform)?
